config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about', as:'about'
  resources :users, only: [:index, :show, :edit]
  resources :books, only: [:index, :show, :edit]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/NoImage.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
  end

  def show
  end

  def edit
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
  end

  def edit
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag @user.get_profile_image(100, 100) %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        <h2>New Book</h2>
        <%= form_with model: @book do |f| %>
          <%= f.label :Title %>
          <%= f.text_field :title, class: "form-control" %>
          <%= f.label :Opinion %>
          <%= f.text_area :body, class: "form-control" %>
          <%= f.submit "Create Book", class: "btn btn-success" %>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <%= @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                    <%= image_tag book.user.get_profile_image(100, 100) %>
                  <% end %>
                </td>
                <td><%= book.title %></td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/homes/about.html.erb
<p id="notice">
  <div class="container">
    <div class="row">
      <div class="px-3 mx-auto">
        <h1>
          Welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>
          !
        </h1>
      </div>
    </div>
  </div>
</p>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>
        In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>
      <p>you can share and exchange your opinions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <apan>Bookers</apan>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarNabDropdown" aria-controls="navbarNabDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNabDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user), class: "nav-link text-light" do %>
              <i class="fas fa-home"></i>Home
            <% end %>
          </li>
          <li>
            <%= link_to users_path, class: "nav-link text-light" do %>
              <i class="fas fa-users"></i>Users
            <% end %>
          </li>
          <li>
            <%= link_to books_path, class: "nav-link text-light" do %>
              <i class="fas fa-book-open"></i>Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, class: "nav-link text-light" do %>
              <i class="fas fa-sign-out-alt"></i>Log out
            <% end %>
          </li>
        <% else %>
          <ul class="navbar-nav ml-auto">
            <li>
              <%= link_to root_path, class: "nav-link text-light" do %>
                <i class="fas fa-home"></i>Home
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class: "nav-link text-light" do %>
                <i class="fas fa-link"></i>About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                <i class="fas fa-user-plus"></i>Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i>Log in
              <% end %>
            </li>
          </ul>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>